-- MySQL Script generated by MySQL Workbench
-- sáb 10 set 2022 16:28:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`custommer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`custommer` (
  `id_custommer` INT NOT NULL,
  PRIMARY KEY (`id_custommer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seller` (
  `id_seller` INT NOT NULL,
  `identification` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id_product` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_product_seller1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`seller` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `id_cart` INT NOT NULL,
  `custommer_id` INT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_cart`),
  INDEX `fk_cart_custommer1_idx` (`custommer_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_custommer1`
    FOREIGN KEY (`custommer_id`)
    REFERENCES `mydb`.`custommer` (`id_custommer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `id_purchase` INT NOT NULL AUTO_INCREMENT,
  `purchase_date` DATE NOT NULL,
  `cart_id_cart` INT NOT NULL,
  PRIMARY KEY (`id_purchase`, `cart_id_cart`),
  INDEX `fk_purchase_cart_idx` (`cart_id_cart` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_cart`
    FOREIGN KEY (`cart_id_cart`)
    REFERENCES `mydb`.`cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart_has_product` (
  `cart_id_cart` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`cart_id_cart`, `product_id`),
  INDEX `fk_cart_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cart_has_product_cart1_idx` (`cart_id_cart` ASC) VISIBLE,
  CONSTRAINT `fk_cart_has_product_cart1`
    FOREIGN KEY (`cart_id_cart`)
    REFERENCES `mydb`.`cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id_supplier` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_1` VARCHAR(45) NOT NULL,
  `phone_2` VARCHAR(45) NULL,
  `phone_3` VARCHAR(45) NULL,
  PRIMARY KEY (`id_supplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_supplier` (
  `product_id_product` INT NOT NULL,
  `supplier_id_supplier` INT NOT NULL,
  PRIMARY KEY (`product_id_product`, `supplier_id_supplier`),
  INDEX `fk_product_has_supplier_supplier1_idx` (`supplier_id_supplier` ASC) VISIBLE,
  INDEX `fk_product_has_supplier_product1_idx` (`product_id_product` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_supplier_product1`
    FOREIGN KEY (`product_id_product`)
    REFERENCES `mydb`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_supplier_supplier1`
    FOREIGN KEY (`supplier_id_supplier`)
    REFERENCES `mydb`.`supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `id_stock` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_stock` (
  `stock_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `ammount` INT NOT NULL,
  PRIMARY KEY (`stock_id`, `product_id`),
  INDEX `fk_product_has_stock_stock1_idx` (`stock_id` ASC) VISIBLE,
  INDEX `fk_product_has_stock_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_stock_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_stock_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `mydb`.`stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id_person` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `custommer_id_custommer` INT NOT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_custommer1_idx` (`custommer_id_custommer` ASC) VISIBLE,
  CONSTRAINT `fk_person_custommer1`
    FOREIGN KEY (`custommer_id_custommer`)
    REFERENCES `mydb`.`custommer` (`id_custommer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entity` (
  `id_entity` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `since` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_1` VARCHAR(45) NOT NULL,
  `phone_2` VARCHAR(45) NULL,
  `phone_3` VARCHAR(45) NULL,
  `custommer_id_custommer` INT NOT NULL,
  PRIMARY KEY (`id_entity`),
  INDEX `fk_entity_custommer1_idx` (`custommer_id_custommer` ASC) VISIBLE,
  CONSTRAINT `fk_entity_custommer1`
    FOREIGN KEY (`custommer_id_custommer`)
    REFERENCES `mydb`.`custommer` (`id_custommer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_card` (
  `id_payment_card` INT NOT NULL,
  `number` INT NOT NULL,
  `card_owner` VARCHAR(100) NOT NULL,
  `secure_key` INT NOT NULL,
  `custommer_id_custommer` INT NOT NULL,
  PRIMARY KEY (`id_payment_card`),
  INDEX `fk_payment_card_custommer1_idx` (`custommer_id_custommer` ASC) VISIBLE,
  CONSTRAINT `fk_payment_card_custommer1`
    FOREIGN KEY (`custommer_id_custommer`)
    REFERENCES `mydb`.`custommer` (`id_custommer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deliver` (
  `id_deliver` INT NOT NULL AUTO_INCREMENT,
  `track_code` VARCHAR(100) NOT NULL,
  `purchase_id` INT NOT NULL,
  `purchase_cart_id` INT NOT NULL,
  PRIMARY KEY (`id_deliver`, `purchase_id`, `purchase_cart_id`),
  UNIQUE INDEX `track_code_UNIQUE` (`track_code` ASC) VISIBLE,
  INDEX `fk_deliver_purchase1_idx` (`purchase_id` ASC, `purchase_cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliver_purchase1`
    FOREIGN KEY (`purchase_id` , `purchase_cart_id`)
    REFERENCES `mydb`.`purchase` (`id_purchase` , `cart_id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
